"""
Actions that can be taken
"""

CALLED_OVER = 'CALLED_OVER'
ARRIVED = 'ARRIVED'
GOT_FACE = 'GOT_FACE'
READY_TO_LOCK = 'READY_TO_LOCK'
MOVEMENT_DETECTED = 'MOVEMENT_DETECTED'
ALARM_HANDLED = 'ALARM_HANDLED'
FACE_RECOGNISED = 'FACE_RECOGNISED'
WRONG_TABLE = 'WRONG_TABLE'
