"""
Actions that can be taken
"""

CALLED_OVER = 'CALLED_OVER'
ARRIVED = 'ARRIVED'
READY_TO_LOCK = 'READY_TO_LOCK'
MOVEMENT_DETECTED = 'MOVEMENT_DETECTED'
ALARM_HANDLED = 'ALARM_HANDLED'
FACE_RECOGNISED = 'FACE_RECOGNISED'
REJECT_TABLE = 'REJECT_TABLE'
FACE_DETECTED = 'FACE_DETECTED'
