"""
Possible states the system can be in
"""

WAIT_FOR_INSTRUCTION = 'WAIT_FOR_INSTRUCTION'
MOVE_TO_TABLE = 'MOVE_TO_TABLE'
AT_TABLE = 'AT_TABLE'
LOCKING = 'LOCKING'
LOCKED_AND_WAITING = 'LOCKED_AND_WAITING'
ALARM = 'ALARM'
#ALARM_REPORT = 'ALARM_REPORT'
ACCIDENT = 'ACCIDENT'
MOVE_TO_HOME = 'MOVE_TO_HOME'
LOST = 'LOST'
