"""
Possible states the system can be in
"""

WAIT_FOR_INSTRUCTION = 'WAIT_FOR_INSTRUCTION'
MOVE_TO_TABLE = 'MOVE_TO_TABLE'
AT_TABLE = 'AT_TABLE'
LOCKING = 'LOCKING'
LOCKED_AND_WAITING = 'LOCKED_AND_WAITING'
ALARM = 'ALARM'
ALARM_REPORT = 'ALARM_REPORT'
MOVE_TO_HOME = 'MOVE_TO_HOME'
CAUGHT = 'CAUGHT'
LOST = 'LOST'
ACCIDENT = 'ACCIDENT'
THIEF = 'THIEF'
