"""
Possible states the system can be in
"""

AT_HOME = 'AT_HOME'
MOVE_TO_TABLE = 'MOVE_TO_TABLE'
AT_TABLE = 'AT_TABLE'
LOCKED_AND_WAITING = 'LOCKED_AND_WAITING'
ALARM = 'ALARM'
ALARM_REPORT = 'ALARM_REPORT'
MOVE_TO_HOME = 'MOVE_TO_HOME'
LISTENING_FOR_TABLE = 'LISTENING_FOR_TABLE'
